spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/auth
    username:  username
    password:  password
    driverClassName: com.mysql.jdbc.Driver
    maxActive:  50
    maxIdle: 5
    minIdle: 25
    initialSize: 10
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    maxWait: 10000
    template:
    cache: false
  jpa:
    generateDdl: true
    hibernate:
      DdlAuto: update
app:
  serverUrl: "http://auth-server:9000"
  loginClientUrl: "http://127.0.0.1:8080/login/oauth2/code/categories-client-oidc"
  authorizedUrl: "http://127.0.0.1:8080/authorized"
  clientId: "client"
  clientSecret: "{noop}secret"
  oidcClientId: "oidc-client"
  oidcClientSecret: "{noop}oidc-secret"
  androidId: "androidId"
  androidSecret: "{noop}androidSecret"
  username: "username"
  password: "password"
server:
  port: 9000