app:
  serverUrl: "https://auth.josdem.io/"
  clientUrl: "http://localhost:8080/"
  loginClientUrl: "http://localhost:8080/login/oauth2/code/login-client"
  authorizedUrl: "http://localhost:8080/authorized"
  clientId: "client"
  clientSecret: "{noop}secret"
  username: "username"
  password: "password"
server:
  port: 9000