app:
  serverUrl: "http://auth-server:9000"
  clientUrl: "http://localhost:8080/"
  loginClientUrl: "http://127.0.0.1:8080/login/oauth2/code/articles-client-oidc"
  authorizedUrl: "http://localhost:8080/authorized"
  credentialsClientId: "credentials-client"
  credentialsClientSecret: "{noop}credentials-secret"
  authClientId: "articles-client"
  authClientSecret: "{noop}secret"
  username: "username"
  password: "password"
server:
  port: 9000