app:
  serverUrl: "http://localhost:9000/"
  loginClientUrl: "http://127.0.0.1:8080/login/oauth2/code/categories-client-oidc"
  authorizedUrl: "http://127.0.0.1:8080/authorized"
  clientId: "client"
  clientSecret: "{noop}secret"
  oidcClientId: "oidc-client"
  oidcClientSecret: "{noop}oidc-secret"
  username: "username"
  password: "password"
server:
  port: 9000